---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  timeout: 1m0s
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo
    ui:
    #  logo: "https://pbs.twimg.com/media/FRZDohuWQAYMIBu?format=jpg&name=large"
      logo: "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif"
    #  logo: "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_bunny.gif"
    replicaCount: 3
    faults:
      unhealthy: false
      unready: false
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: podinfo.jammy
          paths:
            - path: /
              pathType: ImplementationSpecific
